apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
   annotations: 
     io.cilium/global-service: "true"
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
